### ISSUE TITLE
Missing cluster-reader definition

### ISSUE THREAD

**Issue by stewartadam** [boeboe/docker-bench-security-kubernetes#1]
Can you publish the `cluster-reader` service account YAML?

**Comment by noqcks** [comment]
☝️

**Comment by onpaws** [comment]
I attempted to guess and check what the `cluster-reader` service account might look like. After some Googling around I found a Jenkins [example](https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/kubernetes/service-account.yml) and am trying to gently modify it. Warning: I'm a k8n noob & this could be totally off.

That said, it appears applying this manifest leave things better but not finished. While the docker-bench-security pod does get deployed now, I'm seeing a new error:
`Error connecting to docker daemon (does docker ps work?)`

I think I have to add more permission(s), but not yet sure which ones. 
@boeboe would appreciate your thoughts! :)

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-reader

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create","delete","get","list","patch","update","watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: cluster-reader

```
